package com.crecheconnect.crechemanagement_app

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration

class ChatListActivity : AppCompatActivity() {

    private lateinit var recyclerViewChats: RecyclerView
    private lateinit var chatListAdapter: ChatListAdapter
    private val chatList = mutableListOf<String>()

    private val db = FirebaseFirestore.getInstance()
    private val auth = FirebaseAuth.getInstance()

    private var listenerRegistration: ListenerRegistration? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_chat_list)

        recyclerViewChats = findViewById(R.id.recyclerViewChats)
        recyclerViewChats.layoutManager = LinearLayoutManager(this)

        chatListAdapter = ChatListAdapter(chatList) { otherUserId ->
            val intent = Intent(this, ChatActivity::class.java)
            intent.putExtra("receiverId", otherUserId)
            // You can optionally include receiverName if you store it elsewhere
            startActivity(intent)
        }

        recyclerViewChats.adapter = chatListAdapter

        loadChatsFirestore()
    }

    private fun loadChatsFirestore() {
        val currentUserId = auth.currentUser?.uid ?: return

        // Real-time listener for all chat documents
        listenerRegistration = db.collection("chats")
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    Log.e("ChatListActivity", "Error loading chats", error)
                    Toast.makeText(this, "Failed to load chats", Toast.LENGTH_SHORT).show()
                    return@addSnapshotListener
                }

                if (snapshot != null) {
                    chatList.clear()

                    for (chatDoc in snapshot.documents) {
                        val chatId = chatDoc.id

                        // Firestore chat IDs are generated by combining UIDs like: uid1-uid2
                        if (chatId.contains(currentUserId)) {
                            val otherId = chatId.split("-").firstOrNull { it != currentUserId }
                            if (!otherId.isNullOrEmpty()) {
                                chatList.add(otherId)
                            }
                        }
                    }

                    chatListAdapter.notifyDataSetChanged()
                    Log.d("ChatListActivity", "Chats loaded: ${chatList.size}")
                }
            }
    }

    override fun onDestroy() {
        super.onDestroy()
        listenerRegistration?.remove()
    }
}
